<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Zend_Uri_Exception" namespace="" name="Zend_Uri_Exception" abstract="false" final="false" start="35" end="37">
  <file path="/var/www/_modules/social_integration/trunk/docs/en/phpdox/../../../thirdparty/Zend/Uri" file="Exception.php" realpath="/var/www/_modules/social_integration/trunk/thirdparty/Zend/Uri/Exception.php" size="1105" time="2015-03-14T10:23:59+13:00" unixtime="1426281839" sha1="cbc59dc7fdaed6d66dc60ec237d0fab215382493" relative="thirdparty/Zend/Uri/Exception.php"/>
  <docblock>
    <description compact="Exceptions for Zend_Uri"/>
    <category value="Zend"/>
    <package value="Zend_Uri"/>
    <copyright value="Copyright (c) 2005-2011 Zend Technologies USA Inc. (http://www.zend.com)"/>
    <license name="http://framework.zend.com/license/new-bsd     New BSD License"/>
  </docblock>
  <extends full="Zend_Exception" namespace="" name="Zend_Exception"/>
</class>
