<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Zend_Http_Exception" namespace="" name="Zend_Http_Exception" abstract="false" final="false" start="35" end="36">
  <file path="/var/www/_modules/social_integration/trunk/docs/en/phpdox/../../../thirdparty/Zend/Http" file="Exception.php" realpath="/var/www/_modules/social_integration/trunk/thirdparty/Zend/Http/Exception.php" size="1131" time="2015-03-14T10:23:58+13:00" unixtime="1426281838" sha1="faf8d0cf95ef1dff83ec1bc603baa494700d390f" relative="thirdparty/Zend/Http/Exception.php"/>
  <docblock>
    <description/>
    <category value="Zend"/>
    <package value="Zend_Http"/>
    <subpackage value="Client"/>
    <copyright value="Copyright (c) 2005-2011 Zend Technologies USA Inc. (http://www.zend.com)"/>
    <license name="http://framework.zend.com/license/new-bsd     New BSD License"/>
  </docblock>
  <extends full="Zend_Exception" namespace="" name="Zend_Exception"/>
  <extender full="Zend_Http_Client_Exception" namespace="" name="Zend_Http_Client_Exception"/>
  <extender full="Zend_Http_Client_Adapter_Exception" namespace="" name="Zend_Http_Client_Adapter_Exception"/>
</class>
