<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Zend_Crypt_Math_Exception" namespace="" name="Zend_Crypt_Math_Exception" abstract="false" final="false" start="34" end="36">
  <file path="/var/www/_modules/social_integration/trunk/docs/en/phpdox/../../../thirdparty/Zend/Crypt/Math" file="Exception.php" realpath="/var/www/_modules/social_integration/trunk/thirdparty/Zend/Crypt/Math/Exception.php" size="1130" time="2015-03-14T10:23:59+13:00" unixtime="1426281839" sha1="6cc5e17b28d8e93c367721c9a8f5f06e45847f3c" relative="thirdparty/Zend/Crypt/Math/Exception.php"/>
  <docblock>
    <description/>
    <category value="Zend"/>
    <package value="Zend_Crypt"/>
    <copyright value="Copyright (c) 2005-2011 Zend Technologies USA Inc. (http://www.zend.com)"/>
    <license name="http://framework.zend.com/license/new-bsd     New BSD License"/>
  </docblock>
  <extends full="Zend_Crypt_Exception" namespace="" name="Zend_Crypt_Exception"/>
  <parent full="Zend_Crypt_Exception" namespace="" name="Zend_Crypt_Exception">
    <extends full="Zend_Exception" namespace="" name="Zend_Exception"/>
  </parent>
  <extender full="Zend_Crypt_Math_BigInteger_Exception" namespace="" name="Zend_Crypt_Math_BigInteger_Exception"/>
</class>
